### ISSUE TITLE
Strange error from config_version when doing puppet-apply

### ISSUE THREAD

**Issue by GeoffWilliams** [puppetlabs/control-repo#5]
Running puppet apply results in the following error when running under one of my docker containers - this is after doing `r10k deploy environment -pv`:

```
Error: Execution of config_version command `/etc/puppetlabs/code/environments/production/scripts/config_version.sh /etc/puppetlabs/code/environments production` failed: Execution of '/etc/puppetlabs/code/environments/production/scripts/config_version.sh /etc/puppetlabs/code/environments production' returned 1: /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/rugged-0.21.4/lib/rugged/repository.rb:99:in `lookup': Object not found - failed to find pack entry (a782f44552cc90a6b8645e95a17ead5b36e71b40) (Rugged::OdbError)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/rugged-0.21.4/lib/rugged/repository.rb:99:in `lookup'
	from /etc/puppetlabs/code/environments/production/scripts/config_version.rb:18:in `<main>' on node dockerbuild.lan.asio
```

**Comment by GeoffWilliams** [comment]
Local file appears to have a modification:
```
[root@dockerbuild /]# r10k deploy environment -pv                   
INFO	 -> Deploying environment /etc/puppetlabs/code/environments/production
ERROR	 -> Command exited with non-zero exit code:
Command: git --git-dir /etc/puppetlabs/code/environments/production/.git --work-tree /etc/puppetlabs/code/environments/production checkout 366899a798ba678cb19ad0415a1d5e5e87776ea5
Stderr:
error: Your local changes to the following files would be overwritten by checkout:
	scripts/config_version.sh
Please, commit your changes or stash them before you can switch branches.
Aborting
Exit code: 1
```

Perhaps this causes the above error?  I've simplified my own repo to just use the git command as this is stopping puppet from running

**Comment by npwalker** [comment]
@GeoffWilliams I'm going to close this out it seems like you were hitting an edge case or something specific to your setup.  Let us know if you think this is still an issue.
